name: firefighter
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4
  - altair_saver
  - beautifulsoup4=4.9
  - fiona
  - findspark
  - folium
  - geopandas
  - h5py=2.10
  - ipywidgets=7.5
  - jupyterlab=2.1.3
  - matplotlib-base=3.2
  - networkx
  - nodejs
  - numba=0.48
  - numpy
  - osmnx
  - pandas=1
  - pandas-profiling
  - pip
  - pillow
  - python=3.7
  - pyspark
  - rise
  - scikit-image=0.16
  - scikit-learn=0.22
  - scipy=1.4
  - seaborn=0.10
  - shapely
  - statsmodels=0.11
  - sympy=1.5
  - vega_datasets
  - xlrd=1.2